sudo: required
language: node_js

services:
  - docker

before_install:
  - docker build - t gonzser/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gonzser/docker-react npm test -- --coverage
