# Specify a base image
# Use an existing docker image as a base.
FROM node:alpine

WORKDIR '/app'

# Install some depenendencies
# Step 2: Download and install dependency
COPY package.json .
RUN npm install
COPY ./ ./

# Default command
# Step 3: Tell the image what to do when it starts as container
CMD ["npm", "start"]
